[package]
name = "orchd-adapters"
version.workspace = true
edition.workspace = true

[dependencies]
orchd-core.workspace = true
orchd-proc.workspace = true

serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
time.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true
