[package]
name = "orchd-proc"
version.workspace = true
edition.workspace = true

[dependencies]
orchd-core.workspace = true

secrecy.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tokio-stream.workspace = true
futures.workspace = true
thiserror.workspace = true
tracing.workspace = true

[target.'cfg(unix)'.dependencies]
command-group.workspace = true
nix.workspace = true
